CREATE TABLE IF NOT EXISTS comments (
  review TEXT PRIMARY KEY NOT NULL,
  id TEXT PRIMARY KEY NOT NULL,
  author TEXT NOT NULL,
  posted DATETIME DEFAULT CURRENT_TIMESTAMP,
  message TEXT NOT NULL,
  FOREIGN KEY(review) REFERENCES reviews(id),
  FOREIGN KEY(author) REFERENCES members(username)
) WITHOUT ROWID;
