CREATE TABLE IF NOT EXISTS comments (
  review TEXT NOT NULL,
  id TEXT NOT NULL,
  author TEXT NOT NULL,
  posted DATETIME DEFAULT CURRENT_TIMESTAMP,
  message TEXT NOT NULL,
  PRIMARY KEY(review, id),
  FOREIGN KEY(review) REFERENCES reviews(id),
  FOREIGN KEY(author) REFERENCES members(username)
) WITHOUT ROWID;
