CREATE TABLE IF NOT EXISTS reviews (
  game TEXT PRIMARY KEY NOT NULL,
  author TEXT PRIMARY KEY NOT NULL,
  rating INTEGER NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY(game) REFERENCES games(id),
  FOREIGN KEY(author) REFERENCES members(id)
) WITHOUT ROWID;
