image: node:12

stages:
  - code-testing
  - acceptance-testing
  - staging-server
  - production-server

linting:
  stage: code-testing
  script:
    - npm install
    - npm run linter

unit-testing:
  stage: code-testing
  script:
    - npm install
    - npm test

code-coverage:
  stage: code-testing
  script:
    - npm install
    - npm run coverage
    
puppeteer:
  variables:
    CI: "false"
  image: buildkite/puppeteer:latest
  stage: acceptance-testing
  artifacts:
    paths:
     - test/acceptance/puppeteer/__image_snapshots__/*
    expire_in: 3 days
  script:
    - npm install
    - npm run puppeteer   
    
deploy-staging:
  image: ruby:latest
  stage: staging-server
  only:
    - master
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_STAGING_SERVER --api-key=$HEROKU_API_KEY

deploy-production:
  image: ruby:latest
  only:
    - master
  stage: production-server
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_PRODUCTION_SERVER --api-key=$HEROKU_API_KEY
