const ErrorEnum = {
  USERNAME_MISSING: 'USERNAME_MISSING',
  USERNAME_UNKNOWN: 'USERNAME_UNKNOWN',
  USERNAME_BAD_REGEX: 'USERNAME_BAD_REGEX',
  USERNAME_IN_USE: 'USERNAME_IN_USE',
  USER_NOT_LOADED: 'USER_NOT_LOADED',

  PASSWORD_MISSING: 'PASSWORD_MISSING',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',

  EMAIL_MISSING: 'EMAIL_MISSING',

  GAME_UNKNOWN: 'GAME_UNKNOWN',
  GAME_NOT_LOADED: 'GAME_NOT_LOADED',
  GAME_MISSING: 'GAME_MISSING',
  GAME_TITLE_IN_USE: 'GAME_TITLE_IN_USE',
  GAME_TITLE_MISSING: 'GAME_TITLE_MISSING',
  GAME_SUMMARY_MISSING: 'GAME_SUMMARY_MISSING',
  GAME_THUMBNAIL_MISSING: 'GAME_THUMBNAIL_MISSING',

  has: string => {
    return Object.prototype.hasOwnProperty.call(ErrorEnum, string)
  }
}

Object.freeze(ErrorEnum)
module.exports = ErrorEnum
